### ISSUE TITLE
Mac M1 unable to open 

### ISSUE THREAD

**Issue by iSeekerTW** [SabakiHQ/Sabaki#817]
There's nothing much to explain. Basically I download the latest release (Mac ARM64 version), unzipped it, drag it into the Applications folder, and tried to launch it, but it shows this.
<img width="261" alt="Screen Shot 2021-08-20 at 6 02 33 PM" src="https://user-images.githubusercontent.com/56954729/130217273-1d892903-db9f-43fc-82ec-286a1c271a8c.png">

**Comment by apetresc** [comment]
Uhh that's strange. Looks like a corrupted download. Do you know how to grab an md5sum of the 7zip file?

**Comment by iSeekerTW** [comment]
nope. I tried downloading the file multiple times, from various sources. The same error occured

**Comment by marcadler** [comment]
> Can you try running `openssl dgst -sha256 <path to Sabaki .7z file>` in a Terminal window and pasting the output here? I'm completely baffled - this error seems to indicate the download was just corrupted somehow.

SHA256(/Users/Home/Downloads/sabaki-v0.52.0-mac-arm64.7z)= eaed12087ffcc7621cf8ff19c258d5daea5a5f3ae918f10a759e459605aa56d3

**Comment by iSeekerTW** [comment]
Problem resolved. It was Safari's problem. I used a downloader app "Folx" to download and the problem was solved. Apparently the download has a 100% chance of corrupting when downloading through mac's default browser.

**Comment by apetresc** [comment]
Oh my god you're right. The file has the _exact same_ hash when I download it via Safari vs wget, but the Safari-downloaded version is "corrupt" according to macOS while the wget-downloaded one runs fine.

This is the strangest thing I've ever seen...

**Comment by apetresc** [comment]
Okay after some Googling it seems it's just [this new Gatekeeper behaviour](https://apple.stackexchange.com/a/236357/3681).

I'm still not clear why downloading via Safari makes a difference - there must be some sort of metadata or registry it keeps? - but I guess the solution is the same as a few other Gatekeeper-related problems that exist: we need to sign Sabaki.

That's already an action item for the next release so I guess this issue can be closed now :) Thanks for bringing this additional symptom of Gatekeeper silliness to my attention!

**Comment by iSeekerTW** [comment]
I have turned gatekeeper off ages ago.

**Comment by horaceho** [comment]
Following the suggestion from https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/ I can successfully open Sabaki after removing attributes of the Sabaki.app , i.e.:
```
xattr -cr Sabaki.app 
```

![Screenshot 2021-12-24 at 10 15 23](https://user-images.githubusercontent.com/6657/147307531-488fe6e8-3c9c-469b-a122-22a3da928eae.png)
